name: Tests
on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        php: ['7.3', '7.4', '8.0', '8.1']
        sf_version: ['5.0.*', '5.2.*', '5.4.*', '6.0.*']
        exclude:
          - php: '7.3'
            sf_version: '6.0.*'
          - php: '7.4'
            sf_version: '6.0.*'

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: flex

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SYMFONY_REQUIRE: ${{ matrix.sf_version }}
        run: composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

      - name: Run tests
        env:
          PHP_VERSION: ${{ matrix.php }}
          SYMFONY_REQUIRE: ${{ matrix.sf_version }}
        run: ./vendor/bin/phpunit

  lowest:
    name: Lowest deps
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 7.3
          coverage: pcov

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable --prefer-lowest

      - name: Run tests
        env:
          PHP_VERSION: 7.3
        run: ./vendor/bin/phpunit -v --coverage-text
